
title:              L'arte della felicità
email:              info@matteoricci.net
description:        Il blog che celebra l'arte della felicità, esplorando ogni sfumatura di gioia e benessere per ispirarti a vivere una vita più serena e appagante.
author:             Matteo Ricci
baseurl:            ""
url:                "https://felicita.matteoricci.net"
background:         "/assets/img/homepage-background.jpg"

  

---


# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code
permalink: /:title/

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 

